# Generated by Django 4.1.2 on 2022-10-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_processrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processrecord',
            old_name='timeBegin',
            new_name='timestampBegin',
        ),
        migrations.RenameField(
            model_name='processrecord',
            old_name='timeEnd',
            new_name='timestampEnd',
        ),
        migrations.RemoveField(
            model_name='processrecord',
            name='cpuCycles',
        ),
        migrations.AddField(
            model_name='processrecord',
            name='cpuTimeNs',
            field=models.BigIntegerField(null=True, verbose_name='Процессорное время (нс)'),
        ),
    ]
