# Generated by Django 4.1.2 on 2022-10-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_timebegin_processrecord_timestampbegin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
