# Generated by Django 4.1.2 on 2022-10-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrecord',
            name='osParentPid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='PID родителя'),
        ),
        migrations.AlterField(
            model_name='processrecord',
            name='osPid',
            field=models.BigIntegerField(verbose_name='PID'),
        ),
    ]
