# Generated by Django 4.1.2 on 2022-10-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_processrecord_osparentpid_alter_processrecord_ospid'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrecord',
            name='imageName',
            field=models.CharField(default=None, max_length=512, verbose_name='Процесс'),
            preserve_default=False,
        ),
    ]
