# Generated by Django 4.1.2 on 2022-10-28 08:13

from django.db import migrations


def save_cpu_time_field(apps, schema_editor):
    model = apps.get_model("core", "ProcessRecord")
    for item in model.objects.all():
        #print(item.id)
        item.cpuCycles = item.cpuTimeNs
        item.cpuClockRate = 1000000000
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_processrecord_add_clockRate_cycles'),
    ]

    operations = [
        migrations.RunPython(save_cpu_time_field),
    ]
