# Generated by Django 4.1.2 on 2022-10-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_preserve_old_cputimens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processrecord',
            name='cpuTimeNs',
        ),
    ]
